export default () => [
  { done: true, name: 'Знакомство с HTML/CSS' },
  { done: true, name: 'Основные понятия HTML/CSS' },
  { done: true, name: 'Структура проекта. Валидность. Блочная модель' },
  { done: true, name: 'Стиль кода HTML. Стиль кода CSS. “Вес селекторов”' },
  { done: true, name: 'Практика / PHOTOSHOP - psd header' },
  { done: true, name: 'Практика / PHOTOSHOP - psd header' },
  { done: false, name: 'Псевдоклассы, псевдоэлементы. Флоаты. Позиционирование' },
  { done: false, name: 'Обзор новых семантических тегов. Тени, градиенты, простая анимация' },
  { done: false, name: 'Пиксельная точность. Perfect Pixel' },
  { done: false, name: 'Практика' },
  { done: false, name: 'Практика' },
  { done: false, name: 'Формы. Таблицы' },
  { done: false, name: 'Оптимизация графики. Спрайты' },
  { done: false, name: 'Основы JS: (gallery, popup, accordion) ч.1' },
  { done: false, name: 'Основы JS: (gallery, popup, accordion) ч.2' },
  { done: false, name: 'Шрифты, их подключение. Цвета' },
  { done: false, name: 'Tooltip, DropDown' },
  { done: false, name: 'Резиновая верстка' },
  { done: false, name: 'Основы Адаптивного дизайна/Responsive ч.1' },
  { done: false, name: 'Основы Адаптивного дизайна/Responsive ч.2' },
  { done: false, name: 'CSS-фреймворки на примере Bootstrap ч.1' },
  { done: false, name: 'CSS-фреймворки на примере Bootstrap ч.2' },
  { done: false, name: 'Контрольная работа' },
  { done: false, name: 'Контрольная работа' }
]